### ISSUE TITLE
Several questions

### ISSUE THREAD

**Issue by Darkau** [MX-Futhark/hook-any-text#25]
Hi, 
First thank you for the nice work you did on HAT!

I encountered several problem so far:

Impossible to find the text through CE, I tried long and short sentences, it was not a game listed as incompatible
In another game, each team I press a button, the cheat window doesn't follow.
In another game, I had a huge error message coming from HAT when I loaded the game, the message told me to screen it and send it but I don't know if here is the right place.

Is it possible to communicate through a forum or discord?
Thank you and sorry for the bother

**Comment by MX-Futhark** [comment]
Hello Darkau, thank you for your interest.

This is indeed not the place for questions. You can send me an email at `mxfuthark @ gmail.com`.

Note that HAT assumes the text transits in memory in a way that can be searched in Cheat Engine. In many games, it is not the case. In other games, entire chapters are stored at once (hence "the cheat window doesn't follow"). For such games, HAT is not the right tool, and there may be no right tool except maybe an OCR, for example Capture2Text.

What should not have happened, however, is the error message. Can you please provide the following information by email?
- The screenshot of the error
- The version of Hook Any Text you are using
- The version of Cheat Engine
- The game you are trying to play, on which emulator, on which version of this emulator
- The steps you took before the message popped up.

Yes I know it's a lot, but I can't do much without it.

Thank you in advance. Closing this issue now.
