### ISSUE TITLE
Pcsx2 - Rupan Sansei - Columbus no isan wa ake ni somaru

### ISSUE THREAD

**Issue by emanuelect** [MX-Futhark/hook-any-text#31]
Hi, I'm trying to use, hook any text on this ps2 game of lupin, released only in Japanese, but I can't get it to work.  Can you make it compatible with this game?

**Comment by MX-Futhark** [comment]
Hi, I’m afraid the issue you are facing is exceedingly common with PS2 games. If the text data does not transit in memory in a way that is easy to detect, or if the game uses a proprietary encoding, then I’m afraid there is not much hook any text can do for you.

Thank you for your interest in the project, and sorry for the inconvenience.
